[package]
name = "sx12xx"
version = "0.1.3"
authors = ["Louis Thiery <louis@helium.com>"]
edition = "2018"
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
license = "Apache 2.0"
readme = "README.md"
description = "Rust Wrapper SX12xx"

[dependencies]
sx12xx-sys = {path = "./sx12xx-sys", version = "0.1.0"}
libm = "0.1.4"
heapless = "0.5.4"
as-slice = "*"
[dependencies.lorawan-device]
git = "https://github.com/helium/rust-lorawan.git"
default-features = false
branch = "lthiery/selectable-device-regions"

[dependencies.lorawan-crypto]
git = "https://github.com/lthiery/rust-lorawan-crypto.git"
branch = "lthiery/new-deps"

[profile.dev]
opt-level = "s"

[profile.release]
incremental   = false
codegen-units = 1
lto           = true
opt-level     = "s"

[dev-dependencies]
cortex-m = {version = "0.6.0", features = ["const-fn"] }
cortex-m-rt = "0.6.7"
cortex-m-semihosting = "0.3.2"
cortex-m-rtic = "0.5.3"
void = { version = "1.0.2", default-features = false }
cast = { version = "0.2.2", default-features = false }
panic-ramdump = "0.1.1"
embedded-hal = { version = "0.2.3", features = ["unproven"] }
nb = "0.1.2"

[dev-dependencies.lorawan-device ]
git = "https://github.com/helium/rust-lorawan.git"
default-features = false
branch = "lthiery/selectable-device-regions"

[dev-dependencies.lorawan-encoding ]
git = "https://github.com/helium/rust-lorawan.git"
default-features = false
branch = "lthiery/selectable-device-regions"

[dev-dependencies.stm32l0xx-hal]
git                    = "https://github.com/stm32-rs/stm32l0xx-hal.git"
features               = ["stm32l0x2","rt", "io-STM32L071"]
version                = "0.7"

